version: '2.1'

services:

  identifying_db_api:
    image: registree/identifying-db-api:latest
    ports:
      - "8001:8000"
    env_file:
      - api.env
    depends_on:
      - mongodb
    networks:
      - backbone
      - apiaggregator_interconnector

  mongodb:
    image: mongo:3.6
    command: mongod
    env_file:
      - mongo.env
    networks:
      - backbone
    volumes:
      - ./mongodata:/data/db
      
networks: 
  backbone:
    driver: bridge
  apiaggregator_interconnector:
    external: true
    
