version: '2.1'

services:

  identifying_db_api:
    image: registree/identifying-db-api:latest
    ports:
      - "8001:8000"
    environment:
      AUTH0_DOMAIN: "registree.eu.auth0.com"
      API_IDENTIFIER: "https://registree.rocks/apis"
      ALGORITHMS: "['RS256']"
    depends_on:
      - mongodb
    networks:
      - backbone
      - apiaggregator_interconnector

  mongodb:
    image: mongo:3.6
    command: mongod
    networks:
      - backbone
    volumes:
      - ./mongodata:/data/db
      
networks: 
  backbone:
    driver: bridge
  apiaggregator_interconnector:
    external: true
    
