openapi: 3.0.0
info:
  description: ''
  version: 1.1.0
  title: Identifying DB API
tags:
  - name: Identifying DB API
    description: ''
paths:
  /student/create:
    post:
      tags:
        - student
      summary: create a new student entry
      description: ''
      operationId: swagger_server.controllers.identifying_db_API_functions.create_new_student_entry
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
        description: >-
          University name and student entry that needs to be added to the
          university collection
        required: true

  /student/create_many:
    post:
      tags:
        - student
      summary: bulk create new student entries
      description: ''
      operationId: swagger_server.controllers.identifying_db_API_functions.bulk_create_student_entries
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Students'
        description: >-
          University name and student entries that needs to be added to the
          university collection
        required: true

  /student/update_id:
    post:
      tags:
        - student
      summary: update a student's id
      description: ''
      operationId: swagger_server.controllers.identifying_db_API_functions.update_id
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateId'
        description: University name and old id
        required: true

  /student/update_address:
    post:
      tags:
        - student
      summary: update a student's address
      description: ''
      operationId: swagger_server.controllers.identifying_db_API_functions.update_address
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAddress'
        description: 'University name, id, and new address'
        required: true

  /student/delete/{id}:
    delete:
      tags:
        - student
      summary: delete a student entry
      description: ''
      operationId: swagger_server.controllers.identifying_db_API_functions.delete_student_entry
      parameters:
        - in: path
          name: id
          required: true
          description: student's id
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict

  /student/all:
    get:
      tags:
        - student
      summary: retrieve all students belonging to one university
      description: ''
      operationId: swagger_server.controllers.identifying_db_API_functions.get_all_students
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict

  /student/by_db_id:
    get:
      tags:
        - student
      summary: retrieve one student by his/her database id
      description: ''
      operationId: swagger_server.controllers.identifying_db_API_functions.get_student_by_db_id
      parameters:
        - in: query
          name: db_id
          required: true
          description: student's database id
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict

  /student/bulk_by_db_id:
    post:
      tags:
        - student
      summary: retrieve students by their database id
      description: ''
      operationId: swagger_server.controllers.identifying_db_API_functions.bulk_get_students_by_id
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkGetStudents'
        description: 'University name, student database ids'
        required: true

  /student/bulk_emails:
    post:
      tags:
        - student
      summary: retrieve student email addresses by their db ids
      description: ''
      operationId: swagger_server.controllers.identifying_db_API_functions.bulk_get_student_emails_by_id
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkGetStudents'
        description: 'University name, student database ids'
        required: true

  /student/by_first_name:
    get:
      tags:
        - student
      summary: retrieve all students with a particular first name
      description: ''
      operationId: swagger_server.controllers.identifying_db_API_functions.get_students_by_first_name
      parameters:
        - in: query
          name: first_name
          required: true
          description: student's first name
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict

  /student/by_last_name:
    get:
      tags:
        - student
      summary: retrieve all students with a particular last name
      description: ''
      operationId: swagger_server.controllers.identifying_db_API_functions.get_students_by_last_name
      parameters:
        - in: query
          name: last_name
          required: true
          description: student's last name
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict

  /student/by_gender:
    get:
      tags:
        - student
      summary: retrieve all students with a particular gender
      description: ''
      operationId: swagger_server.controllers.identifying_db_API_functions.get_students_by_gender
      parameters:
        - in: query
          name: gender
          required: true
          description: student's gender
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict

  /student/by_race:
    get:
      tags:
        - student
      summary: retrieve all students with a particular race
      description: ''
      operationId: swagger_server.controllers.identifying_db_API_functions.get_students_by_race
      parameters:
        - in: query
          name: race
          required: true
          description: student's race
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict

  /student/by_student_id:
    get:
      tags:
        - student
      summary: retrieve one student by his/her student id
      description: ''
      operationId: swagger_server.controllers.identifying_db_API_functions.get_students_by_student_id
      parameters:
        - in: query
          name: student_id
          required: true
          description: student's id
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict

  /student/by_address:
    get:
      tags:
        - student
      summary: retrieve students by address characteristica. Can by street or city.
      description: ''
      operationId: swagger_server.controllers.identifying_db_API_functions.get_students_by_address
      parameters:
        - in: query
          name: address
          required: true
          description: student's address part
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict

  /student/by_birth_year:
    get:
      tags:
        - student
      summary: retrieve students by their birth year
      description: ''
      operationId: swagger_server.controllers.identifying_db_API_functions.get_students_by_birth_year
      parameters:
        - in: query
          name: birth_year
          required: true
          description: student's birth year
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict

  /student/by_birth_month:
    get:
      tags:
        - student
      summary: retrieve students by their birth month
      description: ''
      operationId: swagger_server.controllers.identifying_db_API_functions.get_students_by_birth_month
      parameters:
        - in: query
          name: birth_month
          required: true
          description: student's birth month
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict

servers:
  - url: 'http://localhost:8000'
components:
  schemas:
    Student:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        date_of_birth:
          type: string
        gender:
          type: string
        race:
          type: string
        address:
          type: string
        student_id:
          type: string
      xml:
        name: Student
    Students:
      type: array
      items:
        type: object
        properties:
          first_name:
            type: string
          last_name:
            type: string
          date_of_birth:
            type: string
          gender:
            type: string
          race:
            type: string
          address:
            type: string
          student_id:
            type: string
      xml:
        name: Students
    UpdateId:
      type: object
      properties:
        id:
          type: string
      xml:
        name: UpdateId
    UpdateAddress:
      type: object
      properties:
        id:
          type: string
        address:
          type: string
      xml:
        name: UpdateAddress
    BulkGetStudents:
      type: object
      properties:
        db_ids:
          type: array
          items:
            type: string
      xml:
        name: BulkGetStudents
